openapi: 3.0.0
info:
  title: Booking Data Ingestion System API
  description: API documentation for the Booking Data Ingestion System
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Development server

components:
  schemas:
    Booking:
      type: object
      required:
        - bookingId
        - customerName
        - bookingDate
        - amount
        - vendor
      properties:
        bookingId:
          type: string
          description: Unique identifier for the booking
        customerName:
          type: string
          description: Name of the customer
        bookingDate:
          type: string
          format: date-time
          description: Date and time of the booking
        amount:
          type: number
          description: Booking amount
        vendor:
          type: object
          required:
            - name
            - type
          properties:
            name:
              type: string
              description: Name of the vendor
            type:
              type: string
              enum: [AIRLINE, HOTEL]
              description: Type of vendor
        createdAt:
          type: string
          format: date-time
          description: Timestamp of record creation
        updatedAt:
          type: string
          format: date-time
          description: Timestamp of last update

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message

paths:
  /bookings:
    post:
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get all bookings
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: Filter by booking date
        - in: query
          name: vendor
          schema:
            type: string
          description: Filter by vendor name
      responses:
        '200':
          description: List of bookings
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Booking'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bookings/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Booking ID
    
    get:
      summary: Get a specific booking
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a booking
      responses:
        '200':
          description: Booking deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Booking deleted successfully
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'