name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies and generate package-lock.json
      run: npm install
    
    - name: Create .env file
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        # Create deployment script
        echo '#!/bin/bash
        set -e  # Exit on error
        
        # SSH into instance and setup PM2 if not installed
        ssh -i ~/.ssh/deploy_key ${EC2_USERNAME}@${EC2_HOST} "
          # Install PM2 if not exists
          if ! command -v pm2 &> /dev/null; then
            echo \"Installing PM2...\"
            sudo npm install -g pm2
          fi
          
          # Create app directory if not exists
          mkdir -p ~/app
        "
        
        # Copy new files
        rsync -av --progress \
          -e "ssh -i ~/.ssh/deploy_key" \
          --exclude=".git" \
          --exclude="node_modules" \
          --exclude=".env" \
          ./ ${EC2_USERNAME}@${EC2_HOST}:~/app/
        
        # SSH into instance and update application
        ssh -i ~/.ssh/deploy_key ${EC2_USERNAME}@${EC2_HOST} "
          cd ~/app && \
          npm install && \
          pm2 describe app > /dev/null 2>&1 && \
          pm2 restart app || \
          pm2 start src/app.js --name app
        "' > deploy.sh
        
        chmod +x deploy.sh
        ./deploy.sh